### Test the dataset class

In [1]:
import sys
import os
project_path = os.path.abspath("../src/")
print(project_path)

C:\Users\yashr\Documents\ml_deeplense\src


In [2]:
from torch.utils.data import DataLoader

In [3]:
sys.path.append(project_path)

In [4]:
from dataset import LensDataset

In [8]:
images_path = "../data/processed/all_train_data.npy"
labels_path = "../data/processed/all_train_labels.npy" 
train_data = LensDataset(images_path, labels_path)

In [10]:
print(train_data.__len__())
X_sample, y_sample = train_data.__getitem__(3)
print(X_sample.shape)
print(y_sample.shape)

30000
torch.Size([1, 150, 150])
torch.Size([])


### Load the model

In [5]:
from model import CNNmodel

In [6]:
model = CNNmodel()
print(model)
print(model.parameters())

CNNmodel(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (cnn_layers): Sequential(
    (0): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): ReLU()
    (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU()
    (8): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (fc_layers): Sequential(
    (0): Linear(in_features=41472, out_features=256, bias=True)
    (1): ReLU()
    (2): Linear(in_features=256, out_features=3, bias=True)
  )
)
<generator object Module.parameters at 0x0000024092BBDC40>


In [7]:
from train import train_model

In [ ]:
train_model()

Epoch [1/5], Loss: 1.0992


In [5]:
from model import CNNmodel

In [6]:
model = CNNmodel()
print(model)

CNNmodel(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (cnn_layers): Sequential(
    (0): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): ReLU()
    (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU()
    (8): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (fc_layers): Sequential(
    (0): Linear(in_features=41472, out_features=256, bias=True)
    (1): ReLU()
    (2): Linear(in_features=256, out_features=3, bias=True)
  )
)


In [24]:
train_load = DataLoader(train_data, batch_size=32, shuffle=True)

In [25]:
print(train_load)

In [26]:
i = 0
for images, labels in train_load:
    print(labels)
    print(i)
    i = i + 1



tensor([1, 2, 2, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 1, 1,
        1, 1, 2, 1, 2, 1, 0, 1])
0
tensor([2, 2, 1, 1, 0, 1, 0, 0, 2, 2, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 2, 0, 1, 0,
        0, 0, 1, 0, 0, 1, 1, 0])
1
tensor([2, 2, 2, 0, 0, 1, 0, 2, 2, 2, 1, 2, 1, 0, 2, 0, 0, 1, 1, 1, 1, 2, 2, 0,
        1, 1, 1, 2, 2, 2, 2, 1])
2
tensor([1, 0, 1, 1, 1, 2, 0, 2, 2, 0, 0, 2, 1, 2, 0, 0, 2, 1, 2, 2, 0, 0, 0, 0,
        2, 2, 0, 0, 0, 1, 2, 1])
3
tensor([1, 0, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 0, 2, 2, 2, 0, 2, 1, 1,
        0, 1, 1, 1, 0, 1, 0, 2])
4
tensor([2, 0, 1, 0, 1, 1, 1, 1, 1, 2, 1, 2, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 2, 0,
        1, 0, 2, 2, 2, 1, 1, 2])
5
tensor([2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 2, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 1, 1, 2,
        0, 1, 1, 0, 1, 1, 2, 2])
6
tensor([0, 1, 2, 0, 2, 2, 2, 1, 1, 2, 0, 1, 0, 2, 1, 0, 2, 2, 1, 0, 0, 0, 2, 1,
        0, 1, 2, 1, 0, 0, 2, 0])
7
tensor([1, 1, 0, 1, 2, 2, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 2, 2, 2, 1, 0,


torch.Size([16, 3])